### ISSUE TITLE
1.7.95 throw error when nodejs app start

### ISSUE THREAD

**Issue by 86chenjie** [ccxt-dev/ccxt#222]
D:\workspace\learn\backend\crypto-api\node_modules\_ccxt@1.7.95@ccxt\ccxt.js:425
                    let partial = async params => this[methodName] (url, type, uppercaseMethod, params)
                                        ^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\workspace\learn\backend\crypto-api\dist\server\controllers\exchange.controller.js:7:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\workspace\learn\backend\crypto-api\dist\server\routes\exchange.route.js:23:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
[11:16:41] [nodemon] app crashed - waiting for file changes before starting...

**Comment by kroitor** [comment]
Hi! What's your version of Node.js?

**Comment by 86chenjie** [comment]
$ node -v
v6.10.3

**Comment by kroitor** [comment]
Can you update it to 7.6+?

**Comment by 86chenjie** [comment]
yes. update fix. thanks!

**Comment by kroitor** [comment]
@86chenjie thank you for reporting!

**Comment by kroitor** [comment]
@86chenjie Are you familiar with the async/await syntax, btw? Because it's much more convenient than `.then()`, as we think. Makes it much shorter in code, much more readable and maintainable.
