### ISSUE TITLE
cryptopia loadMarkets fail

### ISSUE THREAD

**Issue by 86chenjie** [ccxt-dev/ccxt#223]
D:\workspace\learn\backend\crypto-api\node_modules\_node-fetch@2.0.0-alpha.8@node-fetch\lib\index.js:705
                throw new TypeError(`${value} is not a legal HTTP header value`);
                ^

TypeError: ___utmvaBmuYcMIB=CZYjKoA; path=/; Max-Age=900 is not a legal HTTP header value
    at sanitizeValue (D:\workspace\learn\backend\crypto-api\node_modules\_node-fetch@2.0.0-alpha.8@node-fetch\lib\index.js:705:9)
    at Headers.append (D:\workspace\learn\backend\crypto-api\node_modules\_node-fetch@2.0.0-alpha.8@node-fetch\lib\index.js:844:38)
    at ClientRequest.<anonymous> (D:\workspace\learn\backend\crypto-api\node_modules\_node-fetch@2.0.0-alpha.8@node-fetch\lib\index.js:1320:15)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at TLSSocket.Readable.push (_stream_readable.js:211:10)
    at TLSWrap.onread (net.js:585:20)

**Comment by kroitor** [comment]
Do you have ccxt installed from a local working copy of a repository or from npm?
If it is in your local repo, can you please try the following to see if that is an old modules / cache problem after updating to newer Node?
```
# in ccxt repo:
rm -rf ./node_modules
npm cache clean --force 
npm install
```

**Comment by 86chenjie** [comment]
worked. thanks
