### ISSUE TITLE
Binance certificate

### ISSUE THREAD

**Issue by ivicaca** [ccxt-dev/ccxt#227]
Calling method for binance raises certificate_verify_error  e.g. 
`ccxt.binance().fetch_ticker('BTC/USDT')`
raises [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)

Headers:
{'User-Agent': 'ccxt/1.7.110 (+https://github.com/kroitor/ccxt) Python/3.6.2', 'Accept-Encoding': 'gzip, deflate'}

**Comment by kroitor** [comment]
Hi! Thanks for reporting! Can you please try these two scripts and report if both of them work or not:

```Python
import ccxt
ccxt.binance().fetch_ticker('BTC/USDT')
```

and

```Python
import ccxt
binance = ccxt.binance({'proxy': 'https://cors-anywhere.herokuapp.com/'})
# or 
# binance = ccxt.binance({'proxy': 'https://crossorigin.me/'})
binance.fetch_ticker('BTC/USDT')
```

These scripts will show if you are able to reach binance directly and if you have the same problem when reaching it via a proxy. Standing by for your reply.

**Comment by kroitor** [comment]
Also, this one can help, though, I don't know what OS you're using:
https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify

I'm on Python 3.6.1. Just tested binance and it worked normally from my location (without using any proxies). This might be specific to your Python install. We need more info about your environment to be able to help you with that. In the meantime, I'm downloading Python 3.6.2 to see if minor version makes a difference.

**Comment by kroitor** [comment]
<img width="732" alt="screen shot 2017-09-22 at 20 12 35" src="https://user-images.githubusercontent.com/1294454/30756213-6aaec8cc-9fd2-11e7-9041-8b37d53f6eeb.png">

```
Certificate verification and OpenSSL

**NEW** This variant of Python 3.6 now includes its own private copy of OpenSSL 1.0.2. 
 Unlike previous releases, the deprecated Apple-supplied OpenSSL libraries are no longer used.  
This also means that the trust certificates in system and user keychains managed by the Keychain 
Access application and the security command line utility are no longer used as defaults by the 
Python ssl module.  For 3.6.0, a sample command script is included in /Applications/Python 3.6 to 
install a curated bundle of default root certificates from the third-party certifi package 
(https://pypi.python.org/pypi/certifi).  If you choose to use certifi, you should consider 
subscribing to the project's email update service to be notified when the certificate bundle 
is updated.
```

**Comment by kroitor** [comment]
Ok, here's the update. I installed a fresh distrib of Python 3.6.2 on my Mac, and I was able to reproduce the bug. Also, note that Binance does not have `BTC/USD`, they only offer `BTC/USDT` (Tether USD).

Here's my output:

```
mbp:ccxt igorkroitor$ python3 
Python 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> binance = ccxt.binance()
>>> binance.symbols
['BCH/BTC', 'BNB/BTC', 'BNB/ETH', 'BNT/ETH', 'BTC/USDT', 'BTM/ETH', 'DNT/ETH', 'EOS/ETH', 
'ETH/BTC', 'ETH/USDT', 'GAS/BTC', 'HCC/BTC', 'HSR/BTC', 'ICN/ETH', 'LTC/BTC', 'MCO/ETH', 
'NEO/BTC', 'OAX/ETH', 'QTUM/ETH', 'SNT/ETH']
>>> binance.fetch_ticker('BTC/USDT')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/igorkroitor/ccxt/ccxt/exchange.py", line 235, in fetch
    response = opener.open(request, timeout=int(self.timeout / 1000))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/igorkroitor/ccxt/ccxt/exchanges.py", line 1272, in fetch_ticker
    'symbol': market['id'],
  File "/Users/igorkroitor/ccxt/ccxt/exchanges.py", line 1461, in request
    response = self.fetch(url, method, headers, body)
  File "/Users/igorkroitor/ccxt/ccxt/exchange.py", line 245, in fetch
    self.raise_error(ExchangeNotAvailable, url, method, e)
  File "/Users/igorkroitor/ccxt/ccxt/exchange.py", line 201, in raise_error
    details,
ccxt.errors.ExchangeNotAvailable: binance GET 
https://www.binance.com/api/v1/ticker/24hr?symbol=BTCUSDT 
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)>
>>> 

```

I'll find a way to make it work either by changing our code or by running that script they mentioned, and I'll post my further results here soon.

**Comment by kroitor** [comment]
Ok, here's what I did:

1. Go to `/Applications/Python\ 3.6/` and run a shell script from there:

    ```
    mbp:~ igorkroitor$ cd /Applications/Python\ 3.6/
    mbp:Python 3.6 igorkroitor$ ls -alh
    total 592
    drwxr-xr-x@  10 root  wheel   340B Sep 22 20:17 .
    drwxrwxr-x+ 105 root  admin   3.5K Sep 22 20:16 ..
    drwxr-xr-x    3 root  wheel   102B Sep 22 20:17 IDLE.app
    -rw-r--r--@   1 root  wheel     0B Jul 17 06:14 Icon?
    -rwxr-xr-x    1 root  wheel   1.4K Jul 17 06:14 Install Certificates.command
    -rw-r--r--    1 root  wheel    13K Jul 17 06:14 License.rtf
    lrwxr-xr-x    1 root  wheel    98B Sep 22 20:17 Python Documentation.html -> /Library/Frameworks/Python.framework/Versions/3.6/Resources/English.lproj/Documentation/index.html
    drwxr-xr-x    3 root  wheel   102B Sep 22 20:17 Python Launcher.app
    -rw-r--r--    1 root  wheel   4.4K Jul 17 06:14 ReadMe.rtf
    -rwxr-xr-x    1 root  wheel   2.5K Jul 17 06:14 Update Shell Profile.command
    ```

2. Here's how contents of that script look like:

    ```shell
    mbp:Python 3.6 igorkroitor$ cat Install\ Certificates.command 
    #!/bin/sh

    /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 << "EOF"

    # install_certifi.py
    #
    # sample script to install or update a set of default Root Certificates
    # for the ssl module.  Uses the certificates provided by the certifi package:
    #       https://pypi.python.org/pypi/certifi

    import os
    import os.path
    import ssl
    import stat
    import subprocess
    import sys

    STAT_0o775 = ( stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR
                | stat.S_IRGRP | stat.S_IWGRP | stat.S_IXGRP
                | stat.S_IROTH |                stat.S_IXOTH )

    def main():
        openssl_dir, openssl_cafile = os.path.split(
            ssl.get_default_verify_paths().openssl_cafile)

        print(" -- pip install --upgrade certifi")
        subprocess.check_call([sys.executable,
            "-E", "-s", "-m", "pip", "install", "--upgrade", "certifi"])

        import certifi

        # change working directory to the default SSL directory
        os.chdir(openssl_dir)
        relpath_to_certifi_cafile = os.path.relpath(certifi.where())
        print(" -- removing any existing file or link")
        try:
            os.remove(openssl_cafile)
        except FileNotFoundError:
            pass
        print(" -- creating symlink to certifi certificate bundle")
        os.symlink(relpath_to_certifi_cafile, openssl_cafile)
        print(" -- setting permissions")
        os.chmod(openssl_cafile, STAT_0o775)
        print(" -- update complete")

    if __name__ == '__main__':
        main()
    EOF
    ```

3. I launched it by typing:

    ```shell
    mbp:Python 3.6 igorkroitor$ ./Install\ Certificates.command 
    ```

4. Here's the output of it:

    ```shell
    -- pip install --upgrade certifi
    Collecting certifi
    Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
    Installing collected packages: certifi
    Successfully installed certifi-2017.7.27.1
    -- removing any existing file or link
    -- creating symlink to certifi certificate bundle
    -- setting permissions
    -- update complete
    ```

5. And, after that, tested Binance again:

    ```
    mbp:Python 3.6 igorkroitor$ cd ~/ccxt
    mbp:ccxt igorkroitor$ python3
    Python 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06) 
    [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import ccxt
    >>> ccxt.binance().fetch_ticker('BTC/USDT')
    {'timestamp': 1506101425353, 'datetime': '2017-09-22T17:30:25.000Z', 'high': 3750.0, 
    'low': 3505.55, 'bid': 3520.01, 'ask': 3537.21, 'vwap': 3623.80101743, 'open': 3680.0, 
    'close': 3700.0, 'first': None, 'last': 3537.41, 'change': -3.875, 'percentage': None, 
    'average': None, 'baseVolume': None, 'quoteVolume': 956.546311, 
    'info': {'priceChange': '-142.59000000', 'priceChangePercent': '-3.875', 
    'weightedAvgPrice': '3623.80101743', 'prevClosePrice': '3700.00000000', 
    'lastPrice': '3537.41000000', 'lastQty': '0.31900100', 'bidPrice': '3520.01000000', 
    'bidQty': '0.31900000', 'askPrice': '3537.21000000', 'askQty': '0.68000000', 
    'openPrice': '3680.00000000', 'highPrice': '3750.00000000', 'lowPrice': '3505.55000000', 
    'volume': '956.54631100', 'quoteVolume': '3466333.49502059', 'openTime': 1506015025353, 
    'closeTime': 1506101425353, 'fristId': 208453, 'lastId': 217170, 'count': 8718}}
    >>> 
    ```

Let us know if this does not help you, in the meantime, I'm closing this issue. Feel free to reopen it if you still have difficulties with it or just ask your questions, we will be happy to answer.

**Comment by walkjivefly** [comment]
I get the same SSL errors on my linux box when using the python embedded in LibreOffice 5.3. Yet the system python works OK. Something to do with them using different versions of OpenSSL I think. Easy workaround was to add

ssl._create_default_https_context = ssl._create_unverified_context

somewhere early in the code before attempting any urllib calls. The workaround came from stackoverflow. Probably there are security implications to it but if you just want the public (no apikey) stuff to work with the least amount of f***ing around then it's an easy win.

**Comment by kroitor** [comment]
@walkjivefly it's better to find and launch that install script to copy their bundled certificates to your LibreOffice environment, or configure LibreOffice somehow, otherwise you will indeed loose security with private calls. I'm not very familiar with LibreOffice, but if there's a built-in terminal there, you can probably install those certificates inside it. Otherwise there should be an option in their preferences or configs. My 2 cents.
