### ISSUE TITLE
Fetch tickers in Bter

### ISSUE THREAD

**Issue by marinsokol5** [ccxt-dev/ccxt#245]
Hi,
There seems to be a problem regarding method `fetch_tickers` in  Bter in async branch.
This is what pops out.

Bter, using python
```
 File "/home/marin/fino/.venv/lib/python3.6/site-packages/ccxt/async/exchanges.py", line 6560, in fetch_tickers
    ids = list(tickers.keys())
AttributeError: 'list' object has no attribute 'keys'
```

**Comment by kroitor** [comment]
Hi! Thx once again! I'll take a look into it and get back to you soon!

**Comment by kroitor** [comment]
Is it repeatable? Can you show verbose output? Because I can't reproduce for now with Python3 from where I am...

**Comment by marinsokol5** [comment]
```
import ccxt.async as ccxt
import asyncio
bter = ccxt.bter()
loop = asyncio.get_event_loop()
loop.run_until_complete(bter.fetch_tickers())
```

Try this.

**Comment by kroitor** [comment]
Well, I did ) I would not ask you if it didn't work on my side... But it does work for me, so we'll need more output, need to know why Bter replies with a non-ticker or an empty response to you... 

![bter-fetch-tickers](https://user-images.githubusercontent.com/1294454/30972394-196f2484-a473-11e7-81ce-2b65457421d2.jpg)

**Comment by marinsokol5** [comment]
![screenshot from 2017-09-28 16-41-09](https://user-images.githubusercontent.com/30181549/30972803-e9105b66-a46b-11e7-825c-e03fa38c3eeb.png)

**Comment by marinsokol5** [comment]
How is this possible?

**Comment by kroitor** [comment]
@marinsokol5 it's hard to tell without verbose output from you ;)

Let's try this now:

```Python
import ccxt.async as ccxt
import asyncio
bter = ccxt.bter({"verbose":True})
loop = asyncio.get_event_loop()
loop.run_until_complete(bter.fetch_tickers())
```

**Comment by marinsokol5** [comment]
This is what I get 
```
loop.run_until_complete(bter.fetch_tickers())
https://data.bter.com/api2/1/marketlist GET https://data.bter.com/api2/1/marketlist 
Request: {'User-Agent': 'ccxt/1.8.63 (+https://github.com/kroitor/ccxt) Python/3.6.2', 'Accept-Encoding': 'gzip, deflate'} None
GET https://data.bter.com/api2/1/marketlist 
Response: {'User-Agent': 'ccxt/1.8.63 (+https://github.com/kroitor/ccxt) Python/3.6.2', 'Accept-Encoding': 'gzip, deflate'} {"result":"true","data":
[{"no":1,"symbol":"ETH","name":"Ethereum","name_en":"Ethereum","name_cn":"\u4ee5\u592a\u5e01","pair":"eth_cny","rate":"1581.00","vol_a":3725.6,"vol_b":"5,753,902","curr_a":"ETH","curr_b":"CNY","curr_suffix":" CNY","rate_percent":"0.00","trend":"flat","supply":76652200,"marketcap":"121,187,128,200","plot":null},{"no":2,"symbol":"BTC","name":"Bitcoin","name_en":"Bitcoin","name_cn":"\u6bd4\u7279\u5e01","pair":"btc_cny","rate":"22039.00","vol_a":163.5,"vol_b":"3,536,799","curr_a":"BTC","curr_b":"CNY","curr_suffix":" CNY","rate_percent":"0.00","trend":"flat","supply":12404200,"marketcap":"273,376,163,800","plot":null},...
]
https://data.bter.com/api2/1/tickers GET https://data.bter.com/api2/1/tickers 
Request: {'User-Agent': 'ccxt/1.8.63 (+https://github.com/kroitor/ccxt) Python/3.6.2', 'Accept-Encoding': 'gzip, deflate'} None
GET https://data.bter.com/api2/1/tickers 
Response: {'User-Agent': 'ccxt/1.8.63 (+https://github.com/kroitor/ccxt) Python/3.6.2', 'Accept-Encoding': 'gzip, deflate'} []
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/home/marin/fino/.venv/lib/python3.6/site-packages/ccxt/async/exchanges.py", line 6560, in fetch_tickers
    ids = list(tickers.keys())
AttributeError: 'list' object has no attribute 'keys'


```

**Comment by kroitor** [comment]
@marinsokol5 yep, they return an empty response to you. Your location may be blocked (or your country/region may be temporarily blocked)... 

Now, let's try this to make sure that we are dealing with rate-limiting in effect:

```Python
import ccxt.async as ccxt
import asyncio
bter = ccxt.bter({"verbose":True, "proxy": "https://cors-anywhere.herokuapp.com/"})
loop = asyncio.get_event_loop()
loop.run_until_complete(bter.fetch_tickers())
```
or
```Python
import ccxt.async as ccxt
import asyncio
bter = ccxt.bter({"verbose":True, "proxy": 'https://crossorigin.me/'})
loop = asyncio.get_event_loop()
loop.run_until_complete(bter.fetch_tickers())
```

Does any of these snippets work for you? If so, this is related to your location. Maybe you have been too aggressive with requests and need to wait a little, until they relax. Or they may be blocking an entire foreign continent. So, what do you see?

**Comment by marinsokol5** [comment]
Yup it passes with a proxy
No idea.
Thank you for you time.

**Comment by kroitor** [comment]
I'll add more robust error handling to Bter so to make the reason more clear. Thx for reporting!
