### ISSUE TITLE
Wallet Withdrawal Problems in several exchanges

### ISSUE THREAD

**Issue by PhinixPhire** [ccxt-dev/ccxt#286]
Good morning, folks,

I've been unable to withdraw from multiple exchanges through ccxt. I know this area is under development, but I wonder if I'm doing something wrong in any of the following circumstances...

my code looks like this...

```
    for x in distribution:
        print "Send " + str(x[0]) + " ETH from " + x[1] + " to " + x[2]
        for y in exchange_list:
            time.sleep(1)
            if y.id == x[1] and y.id != 'bitfinex' and y.hasWithdraw: #Bitfinex temporary excluded
                y.withdraw('ETH', format(x[0], '8f'), x[3])
```

("distribution" is a tuple including the amount I want to move ([x][0]), the exchange to move from ([x][1]) and the exchange to move to ([x][2]), along with the wallet address of the receiving exchange ([x][3]))

exchange_list is a tuple containing the exchange objects. I declare each of them and then put them into exchange_list like so:

```
tidex = ccxt.tidex({
    'apiKey': '[REMOVED]',   
    'secret': '[REMOVED]',
    'nonce': ccxt.Exchange.milliseconds,
    'verbose': True
    })
bittrex = ccxt.bittrex({
    'apiKey': '[REMOVED]',
    'secret': '[REMOVED]'
    })

exchange_list = [bittrex, poloniex, bitfinex, cex, tidex, gdax, binance, hitbtc]
```

Bittrex, Poloniex and GDAX, for example, work great:

('https://bittrex.com/api/v1.1/account/withdraw?nonce=1507376565715&currency=ETH&apikey=[REMOVED]&address=0xf2805cc91932f716cd1b50f2969e96bf9185efc6&quantity=0.1', 'GET', 'https://bittrex.com/api/v1.1/account/withdraw?nonce=1507376565715&currency=ETH&apikey=[REMOVED]&address=0xf2805cc91932f716cd1b50f2969e96bf9185efc6&quantity=0.1', '\nRequest:', {'apisign': 'b5ceefa3f5be426923af84a8b550faf8dee986a6334b44af3165c38f25c1f2ef6d5e2e3677d8f56ad5d2d334472e8fbb72aaa18c731a366af4427ad28a20c422', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'ccxt/1.9.37 (+https://github.com/kroitor/ccxt) Python/2.7.14'}, None)
('GET', 'https://bittrex.com/api/v1.1/account/withdraw?nonce=1507376565715&currency=ETH&apikey=[REMOVED]&address=0xf2805cc91932f716cd1b50f2969e96bf9185efc6&quantity=0.1', '\nResponse:', ['Date: Sat, 07 Oct 2017 11:42:46 GMT\r\n', 'Content-Type: application/json; charset=utf-8\r\n', 'Content-Length: 96\r\n', 'Connection: close\r\n', 'Set-Cookie: __cfduid=d48c9c1ba70925d7a9dab2f37fff406cc1507376566; expires=Sun, 07-Oct-18 11:42:46 GMT; path=/; domain=.bittrex.com; HttpOnly\r\n', 'Cache-Control: private\r\n', 'Content-Encoding: gzip\r\n', 'Strict-Transport-Security: max-age=15768000\r\n', 'X-XSS-Protection: 1; mode=block\r\n', 'X-Content-Type-Options: nosniff\r\n', 'X-Download-Options: noopen\r\n', 'Server: cloudflare-nginx\r\n', 'CF-RAY: 3aa099528dff22c4-LAX\r\n'], u'{"success":true,"message":"","result":{"uuid":"[REMOVED]"}}')
{'info': {u'message': u'', u'result': {u'uuid': u'[REMOVED]'}, u'success': True}, 'id': u'[REMOVED]'}

The following tests were done with the following code to simplify the testing process (replacing gdax with the other ccxt exchange objects):

```
x = (0.1, '0xf2805cc91932f716cd1b50f2969e96bf9185efc6')
print gdax.withdraw('ETH', x[0], x[1])
```

I'm getting errors such as this for Tidex: 

('https://api.tidex.com/tapi', 'POST', 'https://api.tidex.com/tapi', '\nRequest:', {'User-Agent': 'ccxt/1.9.37 (+https://github.com/kroitor/ccxt) Python/2.7.14', 'Content-Type': 'application/x-www-form-urlencoded', 'Accept-Encoding': 'gzip, deflate', 'Key': [REMOVED], 'Sign': '[REMOVED]'}, 'nonce=1507375760&amount=0.034989&coinName=BTC&method=WithdrawCoin&address=19qAGRERXqa9Pe3QvKvKZbRjiSxEyXFvkz')
('POST', 'https://api.tidex.com/tapi', '\nResponse:', ['Date: Sat, 07 Oct 2017 11:29:20 GMT\r\n', 'Content-Type: application/json; charset=utf-8\r\n', 'Transfer-Encoding: chunked\r\n', 'Connection: close\r\n', 'Set-Cookie: __cfduid=[REMOVED]; expires=Sun, 07-Oct-18 11:29:20 GMT; path=/; domain=.tidex.com; HttpOnly\r\n', 'Server: cloudflare-nginx\r\n', 'CF-RAY: 3aa085a8ddbc76d0-LAX\r\n', 'Content-Encoding: gzip\r\n'], u'{"success":0,"code":0,"error":"invalid method"}')
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\Kenneth\eclipse-workspace\Chank\wallet-daemon.py", line 179, in distributeFunds
    distributeBTC()
  File "C:\Users\Kenneth\eclipse-workspace\Chank\wallet-daemon.py", line 138, in distributeBTC
    y.withdraw('BTC', format(x[0], '6f'), x[3])
  File "C:\Python27\lib\site-packages\ccxt\exchanges.py", line 14184, in withdraw
    }, params))
  File "C:\Python27\lib\site-packages\ccxt\exchanges.py", line 14220, in request
    raise ExchangeError(self.id + ' ' + self.json(response))
ExchangeError: tidex {"code":0,"success":0,"error":"invalid method"}

This occurs with Bitfinex (@kroiter is currently looking into this one because I hijacked the thread of Issue#199): 

('https://api.bitfinex.com/v1/withdraw', 'POST', 'https://api.bitfinex.com/v1/withdraw', '\nRequest:', {'User-Agent': 'ccxt/1.9.37 (+https://github.com/kroitor/ccxt) Python/2.7.14', 'X-BFX-PAYLOAD': [REMOVED]=', 'X-BFX-APIKEY': '[REMOVED]', 'Accept-Encoding': 'gzip, deflate', 'X-BFX-SIGNATURE': '[REMOVED]'}, None)
Traceback (most recent call last):
  File "C:\Users\Kenneth\eclipse-workspace\Chank\CCXTtests.py", line 76, in <module>
    print bitfinex.withdraw('ETH', x[0], x[1])
  File "C:\Python27\lib\site-packages\ccxt\exchanges.py", line 2389, in withdraw
    }, params))
  File "C:\Python27\lib\site-packages\ccxt\exchanges.py", line 2424, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Python27\lib\site-packages\ccxt\exchange.py", line 225, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Python27\lib\site-packages\ccxt\exchange.py", line 263, in fetch
    self.handle_rest_errors(e, e.code, text, url, method)
  File "C:\Python27\lib\site-packages\ccxt\exchange.py", line 311, in handle_rest_errors
    self.raise_error(error, url, method, exception if exception else str(http_status_code), details)
  File "C:\Python27\lib\site-packages\ccxt\exchange.py", line 210, in raise_error
    details,
ccxt.errors.ExchangeNotAvailable: bitfinex POST https://api.bitfinex.com/v1/withdraw 400 Bad Request  (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting, 

Also, has anyone got advice for getting around HitBTC's "Main" wallet that receives deposits and the need to transfer to the trading wallet before it's accessible to withdrawal or trade? I'd like to fully automate my trades and will need to move funds around regularly to do so. 

Thanks so much!

**Comment by PhinixPhire** [comment]
Regarding the HitBTC side question, I get this failure because the balance is in the trading wallet, and not available to "Main" (as referred to on the web page)

I tried this:
`y.withdraw('ETH', format(x[0], '8f'), x[3], {'walletselected': 'trading'})`

But no luck.

**Comment by kroitor** [comment]
@PhinixPhire for Tidex, the answer is: https://tidex.com/public-api

![tidex-withdraw](https://user-images.githubusercontent.com/1294454/31307866-e3db0276-ab74-11e7-9fe7-74be8ac0b568.jpg)

So, this issue to me reads like this:
- You have GDAX, Poloniex and Bittrex working, so they are irrelevant to this post.
- You have Tidex not working, because they have not enabled their API withdraw 
- You have a problem withdrawing from Bitfinex
- You have a problem withdrawing from HitBTC

So, of all of the above, we actually have to solve two issues: HitBTC withdraw ([#199]) and Bitfinex withdraw. I'm investigating into them both now.

For HitBTC: can you move your funds to Main and try to withdraw from there without the extra params?

**Comment by PhinixPhire** [comment]
HitBTC works when the balance is in the "Main" wallet. I just performed another test to be sure and it went through. The problem with that is I don't have a means to move the funds between Main and Trading wallets in order to programmatically transfer funds between currencies and exchanges without visiting the site to triage it manually.

**Comment by kroitor** [comment]
@PhinixPhire,

> The problem with that is I don't have a means to move the funds between Main and Trading wallets in order to programmatically transfer funds between currencies and exchanges without visiting the site to triage it manually.

You actually do have all necessary means, because ccxt supports all of their endpoints, including the ones for transferring money between accounts:

```Python
hitbtc.payment_post_transfer_to_trading ({
   'amount': 0.01,
   'currency_code': 'BTC',
})

hitbtc.payment_post_transfer_to_main ({
   'amount': 0.01,
   'currency_code': 'BTC',
})
```

Does this satisfy your requirements for HitBTC ?

**Comment by PhinixPhire** [comment]
Yes, wonderful! That's exactly what I needed for HitBTC. Thank you so much.

**Comment by kroitor** [comment]
Ok, so we're left with Bitfinex remaining? I'll investigate into it.

**Comment by PhinixPhire** [comment]
Yes, that's the only remaining issue. Let me know what you find and how I can be of assistance.

**Comment by kroitor** [comment]
@PhinixPhire does Bitfinex's fetch_balance work for you?

**Comment by PhinixPhire** [comment]
Yes, fetch_balance works fine with Bitfinex and returns data I can verify as true on the site.

**Comment by kroitor** [comment]
@PhinixPhire and do you have funds on your exchange wallet with Bitfinex? Or margin wallet? Or funding wallet?

**Comment by PhinixPhire** [comment]
All in Exchange wallet

**Comment by kroitor** [comment]
@PhinixPhire and API key permissions to withdraw are all set to "write", is that correct?

<img width="650" alt="screen shot 2017-10-07 at 18 23 53" src="https://user-images.githubusercontent.com/1294454/31309309-c3296992-ab8c-11e7-895e-f35098bcf22d.png">

**Comment by PhinixPhire** [comment]
Yes, That's correct

**Comment by kroitor** [comment]
@PhinixPhire ok, I found the bug with Bitfinex `withdraw()` and fixed it. Bitfinex wanted the amount to be of string type, not a number, but now it's all working normally. So, you can use your previous code to test it. Please update to version 1.9.63+ (will be available in 5 minutes) and try again. It should work as well as others. I'm standing by to hear from you on this.

**Comment by kroitor** [comment]
The 1.9.63 build is now there, available for downloading.

**Comment by PhinixPhire** [comment]
I'm still having trouble and I can't figure out if it's a problem at my end...

Verbose output as follows: 

```
Distribute 3.68188142798 ETH to each Exchange
Suggested withdrawals:
Withdrawal (0.000097 ETH) below limit - passing this transfer
Withdrawal (0.003557 ETH) below limit - passing this transfer
Withdrawal (0.000905 ETH) below limit - passing this transfer
Send 0.014654 ETH from bitfinex to poloniex
('https://api.bitfinex.com/v1/withdraw', 'POST', 'https://api.bitfinex.com/v1/withdraw', '\nRequest:', {'User-Agent': 'ccxt/1.9.63 (+https://github.com/kroitor/ccxt) Python/2.7.14', 'X-BFX-PAYLOAD': [REMOVED]', 'X-BFX-APIKEY': '[REMOVED]', 'Accept-Encoding': 'gzip, deflate', 'X-BFX-SIGNATURE': '[REMOVED]'}, None)
('POST', 'https://api.bitfinex.com/v1/withdraw', '\nResponse:', 'Date: Sat, 07 Oct 2017 20:21:57 GMT\r\nContent-Type: application/json; charset=utf-8\r\nTransfer-Encoding: chunked\r\nConnection: close\r\nSet-Cookie: __cfduid=[REMOVED]; expires=Sun, 07-Oct-18 20:21:56 GMT; path=/; domain=.bitfinex.com; HttpOnly\r\nStrict-Transport-Security: max-age=31536000\r\nX-Frame-Options: SAMEORIGIN\r\nX-XSS-Protection: 1; mode=block\r\nX-Content-Type-Options: nosniff\r\nVary: Accept-Encoding\r\nContent-Encoding: gzip\r\nETag: "[REMOVED]"\r\nCache-Control: max-age=0, private, must-revalidate\r\nX-Request-Id: [REMOVED]\r\nX-Runtime: 0.206819\r\nX-Frame-Options: SAMEORIGIN\r\nServer: cloudflare-nginx\r\nCF-RAY: 3aa391d268931401-LAX\r\n', u'[{"status":"success","message":"Your withdrawal request has been successfully submitted.","withdrawal_id":4148145,"fees":"0.01"}]')
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\Kenneth\eclipse-workspace\Chank\wallet-daemon.py", line 198, in fundDistribution
    distributeFunds()
  File "C:\Users\Kenneth\eclipse-workspace\Chank\wallet-daemon.py", line 191, in distributeFunds
    distributeETH()
  File "C:\Users\Kenneth\eclipse-workspace\Chank\wallet-daemon.py", line 185, in distributeETH
    y.withdraw('ETH', format(x[0], '8f'), x[3])
  File "C:\Python27\lib\site-packages\ccxt\exchanges.py", line 2398, in withdraw
    'id': response['withdrawal_id'],
TypeError: list indices must be integers, not str

```

I confirm I have updated to ccxt 1.9.63.

Thanks, @kroitor !

**Comment by PhinixPhire** [comment]
I should note that the withdrawal did go through, but I'm still getting the "integer, not str" error.

**Comment by kroitor** [comment]
@PhinixPhire yeah, I see, will fix right away, give me a few minutes. Thx!

**Comment by kroitor** [comment]
@PhinixPhire ok, should be working, fixed it completely, that was a minor leftover. Sorry for the inconvenience and thx for your patience! You can now use it safely.

**Comment by PhinixPhire** [comment]
Looks good, sir! Thank you very much. I can't express my appreciation enough. All issues in this thread are resolved.

**Comment by kroitor** [comment]
@PhinixPhire Thx for reporting back ) Cheers!

**Comment by wukoujuey** [comment]
I can't believe how terrible people have become in the world, how can a broker call me up and make me believe that I was investing into something genuine, in a couple of months I had been fleeced out of my life savings, till this day haven't even been able to get fully back on my feet. Having taken my time to do some research, I would like to speak with other people who have been through similar experiences, together without a doubt I am sure with like minded minds we can all get our money back. I met with a genius Olivia Teams, who helped me get back on my feet again
Email oliviatrader 44 @"gmail ,com
WhatsApp  +1 (423) 248-2140
