### ISSUE TITLE
How to install this library with IronPython?

### ISSUE THREAD

**Issue by munrocket** [ccxt-dev/ccxt#311]
I am trying to use this library in C# with IronPython.

I ran cmd as administrator, opened directory c:\Program Files (x86)\IronPython 2.7 and executed this lines
```
ipy -X:Frames -m ensurepip
ipy -X:Frames -m pip install --upgrade
pip install ccxt
```
But it seems like ccxt installed not globally. `ipy -X:Frames -m pip install ccxt` not working too.

Also i tryed to download source and execute in ccxt folder
```
python setup.py install
```

But nothing helps. When i am trying to install it through VS2015 in Python Environment i get this error.
```
----- Installing 'ccxt' -----
Unhandled exception:
Traceback (most recent call last):
  File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 182, in run_module
  File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 111, in _get_module_details
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\__init__.py", line 21, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\requests\__init__.py", line 62, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\requests\packages\__init__.py", line 27, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\requests\packages\urllib3\__init__.py", line 8, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 34, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\requests\packages\urllib3\packages\six.py", line 701, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\requests\packages\urllib3\packages\six.py", line 692, in exec_
AttributeError: 'module' object has no attribute '_getframe'
----- Failed to install 'ccxt' -----
```

And this testing project not working
```
import sys
sys.path.append(r'C:\Program Files (x86)\IronPython 2.7\Lib')
import ccxt
print(ccxt.exchanges)
```

**Comment by kroitor** [comment]
Hi! Can you try this: https://github.com/IronLanguages/ironpython2/issues/232#issuecomment-325657801 ?

**Comment by munrocket** [comment]
After two hours of solving this problem i finally get supported exchanges from ccxt with this source.
```
import sys
sys.path.append(r'c:\users\qnxp\appdata\local\programs\python\python36\lib\site-packages')
import ccxt
print(ccxt.exchanges)
```
As i understand i am install ccxt locally. But it works! Thanks!

**Comment by kroitor** [comment]
@munrocket well, pip installed it globally, and didn't install that into python2.7, as you see, it installed into 3.6. That's why you had to add the path to 3.6 to your imports. But if you have it working already, then, I guess, this issue is solved for now?

**Comment by munrocket** [comment]
Your solution was nice. Maybe i will catch this annoying again, but for now i solved this for 3.6.

**Comment by munrocket** [comment]
Two versions of the python in one OS are always trying to confuse you.
I wonder how i launched 3.6 project in 2.7 enviroment without error.

It seems that right installation for IronPython 2.7 is execute this lines in ccxt folder
```
"c:\Program Files (x86)\IronPython 2.7\ipy.exe" -X:Frames setup.py build
"c:\Program Files (x86)\IronPython 2.7\ipy.exe" -X:Frames setup.py build_py
"c:\Program Files (x86)\IronPython 2.7\ipy.exe" -X:Frames setup.py install
```

And than use it with source like this
```
import sys
sys.path.append(r'C:\Program Files (x86)\IronPython 2.7\Lib')

import ccxt
print(ccxt.exchanges)
```

**Comment by kroitor** [comment]
@munrocket thank you very much for this follow up! I'm sure it will be helpful to other users that might run into the same problem with Python on Windows! Your feedback is really appreciated! Cheers!

**Comment by wahyubram82** [comment]
i do this:
ipy -X:Frames -m ensurepip
ipy -X:Frames -m pip install pip --upgrade
ipy -X:Frames -m pip install ccxt

works perfectly...

**Comment by kroitor** [comment]
@wahyubram82 thanks for the hint! Added to our arsenal )
