### ISSUE TITLE
fetch_ticker giving error

### ISSUE THREAD

**Issue by vinaykashyap1206** [ccxt-dev/ccxt#315]
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/arajguru/work/CCPlatform_Private/ccplatform/contrib/live_data_feeders/websocket_thread.py", line 10, in run
    self.wsinstance.connect()
  File "contrib/live_data_feeders/bter_data_feeder.py", line 54, in connect
    temp=self.bter.fetch_ticker(tradepair)
  File "/home/arajguru/work/CCPlatform_Private/venv/local/lib/python2.7/site-packages/ccxt/exchanges.py", line 6791, in fetch_ticker
    'id': market['id'],
TypeError: string indices must be integers, not str

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/arajguru/work/CCPlatform_Private/ccplatform/contrib/live_data_feeders/websocket_thread.py", line 10, in run
    self.wsinstance.connect()
  File "contrib/live_data_feeders/bter_data_feeder.py", line 54, in connect
    temp=self.bter.fetch_ticker(tradepair)
  File "/home/arajguru/work/CCPlatform_Private/venv/local/lib/python2.7/site-packages/ccxt/exchanges.py", line 6791, in fetch_ticker
    'id': market['id'],
TypeError: string indices must be integers, not str

**Comment by kroitor** [comment]
Hi!

1. Can you paste a minimal code snippet demonstrating the problem?
2. What symbol are you using for fetch_tickers with Bter?
3. Did you check all available symbols with Bter to see if your symbol is present there?

**Comment by vinaykashyap1206** [comment]
Hi,
1) Okay so when I initialize my ccxt object :
self.bter=ccxt.bter()
self.bter.load_markets()
and then when I try to fetch the ticket data:
temp=self.bter.fetch_ticker(tradepair)
 This is where it throws this error:
==================================
  File "contrib/live_data_feeders/bter_data_feeder.py", line 55, in connect
    temp=self.bter.fetch_ticker(tradepair)
  File "/home/arajguru/work/CCPlatform_Private/venv/local/lib/python2.7/site-packages/ccxt/exchanges.py", line 6791, in fetch_ticker
    'id': market['id'],
TypeError: string indices must be integers, not str
=================================
2) The symbol I'm using is 'btc_cny' which is my tradepair.

3) Yes  Bter's official website gives this url to return all the trading pairs supported by Bter.
http://data.bter.com/api2/1/pairs. 
And my tradepair is first in that list.

**Comment by kroitor** [comment]
https://github.com/ccxt-dev/ccxt/wiki
https://github.com/ccxt-dev/ccxt/wiki/Manual#markets
https://github.com/ccxt-dev/ccxt/blob/master/examples/py/symbols.py
https://github.com/ccxt-dev/ccxt/wiki/Manual#troubleshooting
https://github.com/ccxt-dev/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by kroitor** [comment]
```
mbp:ccxt igorkroitor$ node examples/js/symbols bter
Instantiating bter exchange (printSymbols @ symbols.js:24)
bter has 83 symbols: BAT/BTC, BAT/CNY, BCH/BTC, BCH/CNY, BTC/CNY, BTS/BTC, BTS/CNY, CNC/BTC, CNC/CNY, CVC/BTC, CVC/CNY, DASH/BTC, DASH/CNY, DNT/BTC, DNT/CNY, DOC/BTC, DOC/CNY, DOGE/BTC, DOGE/CNY, EOS/BTC, EOS/CNY, ETC/BTC, ETC/CNY, ETH/BTC, ETH/CNY, ETP/BTC, ETP/CNY, FTC/BTC, FTC/CNY, HKG/BTC, ICO/BTC, ICO/CNY, IFC/CNY, IFC/LTC, LLT/CNY, LRC/CNY, LTC/BTC, LTC/CNY, MG/BTC, NMC/BTC, NMC/CNY, NXT/BTC, NXT/CNY, OAX/BTC, OMG/BTC, OMG/CNY, PAY/BTC, PAY/CNY, PPC/BTC, PPC/CNY, PST/BTC, PST/CNY, QTUM/BTC, QTUM/CNY, REP/BTC, REP/CNY, SNT/BTC, SNT/CNY, STORJ/BTC, STORJ/CNY, TIPS/CNY, TIPS/LTC, TIX/CNY, TIX/LTC, TNT/CNY, UBC/BTC, XCN/BTC, XCP/BTC, XCP/CNY, XEM/BTC, XEM/CNY, XMR/BTC, XMR/CNY, XPM/BTC, XPM/CNY, XRP/BTC, XRP/CNY, XTC/BTC, XTC/CNY, ZEC/BTC, ZEC/CNY, ZRX/BTC, ZRX/CNY (printSymbols @ symbols.js:36)
limits | precision | id        | symbol    | base  | quote | info           
----------------------------------------------------------------------------
       |           | bat_btc   | BAT/BTC   | BAT   | BTC   | [object Object]
       |           | bat_cny   | BAT/CNY   | BAT   | CNY   | [object Object]
       |           | bcc_btc   | BCH/BTC   | BCH   | BTC   | [object Object]
       |           | bcc_cny   | BCH/CNY   | BCH   | CNY   | [object Object]
       |           | btc_cny   | BTC/CNY   | BTC   | CNY   | [object Object]
       |           | bts_btc   | BTS/BTC   | BTS   | BTC   | [object Object]
       |           | bts_cny   | BTS/CNY   | BTS   | CNY   | [object Object]
       |           | cnc_btc   | CNC/BTC   | CNC   | BTC   | [object Object]
       |           | cnc_cny   | CNC/CNY   | CNC   | CNY   | [object Object]
       |           | cvc_btc   | CVC/BTC   | CVC   | BTC   | [object Object]
       |           | cvc_cny   | CVC/CNY   | CVC   | CNY   | [object Object]
       |           | dash_btc  | DASH/BTC  | DASH  | BTC   | [object Object]
       |           | dash_cny  | DASH/CNY  | DASH  | CNY   | [object Object]
       |           | dnt_btc   | DNT/BTC   | DNT   | BTC   | [object Object]
       |           | dnt_cny   | DNT/CNY   | DNT   | CNY   | [object Object]
       |           | doc_btc   | DOC/BTC   | DOC   | BTC   | [object Object]
       |           | doc_cny   | DOC/CNY   | DOC   | CNY   | [object Object]
       |           | doge_btc  | DOGE/BTC  | DOGE  | BTC   | [object Object]
       |           | doge_cny  | DOGE/CNY  | DOGE  | CNY   | [object Object]
       |           | eos_btc   | EOS/BTC   | EOS   | BTC   | [object Object]
       |           | eos_cny   | EOS/CNY   | EOS   | CNY   | [object Object]
       |           | etc_btc   | ETC/BTC   | ETC   | BTC   | [object Object]
       |           | etc_cny   | ETC/CNY   | ETC   | CNY   | [object Object]
       |           | eth_btc   | ETH/BTC   | ETH   | BTC   | [object Object]
       |           | eth_cny   | ETH/CNY   | ETH   | CNY   | [object Object]
       |           | etp_btc   | ETP/BTC   | ETP   | BTC   | [object Object]
       |           | etp_cny   | ETP/CNY   | ETP   | CNY   | [object Object]
       |           | ftc_btc   | FTC/BTC   | FTC   | BTC   | [object Object]
       |           | ftc_cny   | FTC/CNY   | FTC   | CNY   | [object Object]
       |           | hkg_btc   | HKG/BTC   | HKG   | BTC   | [object Object]
       |           | ico_btc   | ICO/BTC   | ICO   | BTC   | [object Object]
       |           | ico_cny   | ICO/CNY   | ICO   | CNY   | [object Object]
       |           | ifc_cny   | IFC/CNY   | IFC   | CNY   | [object Object]
       |           | ifc_ltc   | IFC/LTC   | IFC   | LTC   | [object Object]
       |           | llt_cny   | LLT/CNY   | LLT   | CNY   | [object Object]
       |           | lrc_cny   | LRC/CNY   | LRC   | CNY   | [object Object]
       |           | ltc_btc   | LTC/BTC   | LTC   | BTC   | [object Object]
       |           | ltc_cny   | LTC/CNY   | LTC   | CNY   | [object Object]
       |           | mg_btc    | MG/BTC    | MG    | BTC   | [object Object]
       |           | nmc_btc   | NMC/BTC   | NMC   | BTC   | [object Object]
       |           | nmc_cny   | NMC/CNY   | NMC   | CNY   | [object Object]
       |           | nxt_btc   | NXT/BTC   | NXT   | BTC   | [object Object]
       |           | nxt_cny   | NXT/CNY   | NXT   | CNY   | [object Object]
       |           | oax_btc   | OAX/BTC   | OAX   | BTC   | [object Object]
       |           | omg_btc   | OMG/BTC   | OMG   | BTC   | [object Object]
       |           | omg_cny   | OMG/CNY   | OMG   | CNY   | [object Object]
       |           | pay_btc   | PAY/BTC   | PAY   | BTC   | [object Object]
       |           | pay_cny   | PAY/CNY   | PAY   | CNY   | [object Object]
       |           | ppc_btc   | PPC/BTC   | PPC   | BTC   | [object Object]
       |           | ppc_cny   | PPC/CNY   | PPC   | CNY   | [object Object]
       |           | pst_btc   | PST/BTC   | PST   | BTC   | [object Object]
       |           | pst_cny   | PST/CNY   | PST   | CNY   | [object Object]
       |           | qtum_btc  | QTUM/BTC  | QTUM  | BTC   | [object Object]
       |           | qtum_cny  | QTUM/CNY  | QTUM  | CNY   | [object Object]
       |           | rep_btc   | REP/BTC   | REP   | BTC   | [object Object]
       |           | rep_cny   | REP/CNY   | REP   | CNY   | [object Object]
       |           | snt_btc   | SNT/BTC   | SNT   | BTC   | [object Object]
       |           | snt_cny   | SNT/CNY   | SNT   | CNY   | [object Object]
       |           | storj_btc | STORJ/BTC | STORJ | BTC   | [object Object]
       |           | storj_cny | STORJ/CNY | STORJ | CNY   | [object Object]
       |           | tips_cny  | TIPS/CNY  | TIPS  | CNY   | [object Object]
       |           | tips_ltc  | TIPS/LTC  | TIPS  | LTC   | [object Object]
       |           | tix_cny   | TIX/CNY   | TIX   | CNY   | [object Object]
       |           | tix_ltc   | TIX/LTC   | TIX   | LTC   | [object Object]
       |           | tnt_cny   | TNT/CNY   | TNT   | CNY   | [object Object]
       |           | ubc_btc   | UBC/BTC   | UBC   | BTC   | [object Object]
       |           | xcn_btc   | XCN/BTC   | XCN   | BTC   | [object Object]
       |           | xcp_btc   | XCP/BTC   | XCP   | BTC   | [object Object]
       |           | xcp_cny   | XCP/CNY   | XCP   | CNY   | [object Object]
       |           | xem_btc   | XEM/BTC   | XEM   | BTC   | [object Object]
       |           | xem_cny   | XEM/CNY   | XEM   | CNY   | [object Object]
       |           | xmr_btc   | XMR/BTC   | XMR   | BTC   | [object Object]
       |           | xmr_cny   | XMR/CNY   | XMR   | CNY   | [object Object]
       |           | xpm_btc   | XPM/BTC   | XPM   | BTC   | [object Object]
       |           | xpm_cny   | XPM/CNY   | XPM   | CNY   | [object Object]
       |           | xrp_btc   | XRP/BTC   | XRP   | BTC   | [object Object]
       |           | xrp_cny   | XRP/CNY   | XRP   | CNY   | [object Object]
       |           | xtc_btc   | XTC/BTC   | XTC   | BTC   | [object Object]
       |           | xtc_cny   | XTC/CNY   | XTC   | CNY   | [object Object]
       |           | zec_btc   | ZEC/BTC   | ZEC   | BTC   | [object Object]
       |           | zec_cny   | ZEC/CNY   | ZEC   | CNY   | [object Object]
       |           | zrx_btc   | ZRX/BTC   | ZRX   | BTC   | [object Object]
       |           | zrx_cny   | ZRX/CNY   | ZRX   | CNY   | [object Object] (printSymbols @ symbols.js:43)
mbp:ccxt igorkroitor$ 
```

**Comment by kroitor** [comment]
<img width="642" alt="screen shot 2017-10-13 at 14 54 18" src="https://user-images.githubusercontent.com/1294454/31545057-6b7f95ce-b026-11e7-9c2e-01ea49c795c1.png">

**Comment by kroitor** [comment]
You should use the `symbol` from the above table as written in the Manual.

**Comment by vinaykashyap1206** [comment]
Great!! Its working now. Thanks a ton!!

**Comment by kroitor** [comment]
@vinaykashyap1206 thanks for reporting back! I'd recommend to read entire Manual to avoid the very basic questions with it. You got all necessary links above ;) Let us know if you have other questions or difficulties with it. Cheers!
