### ISSUE TITLE
Python3 ccxt.async RuntimeError

### ISSUE THREAD

**Issue by dhmk815** [ccxt-dev/ccxt#345]
Hello.
I am using ccxt.async library for fetching bittrex orderbooks.
Here is my code.

```
import asyncio
import ccxt
import ccxt.async as ca
import time

markets = ['BTC-XRP', 'BTC-DASH', 'BTC-LTC', 'BTC-ETC', 'BTC-ETH', 'BTC-BCC', 'BTC-XMR', 'BTC-ZEC',
           'ETH-XRP', 'ETH-DASH', 'ETH-LTC', 'ETH-ETC', 'ETH-BCC', 'ETH-XMR', 'ETH-ZEC',
           'USDT-BTC', 'USDT-XRP', 'USDT-DASH', 'USDT-LTC', 'USDT-ETC', 'USDT-ETH', 'USDT-BCC', 'USDT-XMR', 'USDT-ZEC']

async def getBittrexOrderbooks(bittrex_obj, market):
    ob = await bittrex_obj.fetch_order_book(market=market)
    return ob
    
async def async_main():
    my_bittrex = ca.bittrex()
    
    futures = [asyncio.ensure_future(getBittrexOrderbooks(my_bittrex, market)) for market in markets]
    
    results = await asyncio.gather(*futures)
    
    return results


begin = time.time()

loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)
try:
    ret = loop.run_until_complete(async_main())
except:
    loop.close()

end = time.time()
print(len(ret))
print("Elapsed time: ", end-begin)
```
Until several times when I run this code, there is no error.
But, after several running, I always encounter this RuntimeError message.

```
Fatal write error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fc2347bf390>
transport: <_SelectorSocketTransport fd=21>
Traceback (most recent call last):
  File "/home/dhmk815/.conda/envs/py3/lib/python3.6/asyncio/selector_events.py", line 762, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fc2347bf390>
transport: <_SelectorSocketTransport closing fd=21>
Traceback (most recent call last):
  File "/home/dhmk815/.conda/envs/py3/lib/python3.6/asyncio/selector_events.py", line 762, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dhmk815/.conda/envs/py3/lib/python3.6/asyncio/sslproto.py", line 648, in _process_write_backlog
    self._transport.write(chunk)
  File "/home/dhmk815/.conda/envs/py3/lib/python3.6/asyncio/selector_events.py", line 766, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/home/dhmk815/.conda/envs/py3/lib/python3.6/asyncio/selector_events.py", line 646, in _fatal_error
    self._force_close(exc)
  File "/home/dhmk815/.conda/envs/py3/lib/python3.6/asyncio/selector_events.py", line 658, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/home/dhmk815/.conda/envs/py3/lib/python3.6/asyncio/base_events.py", line 574, in call_soon
    self._check_closed()
  File "/home/dhmk815/.conda/envs/py3/lib/python3.6/asyncio/base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

I don't know what's wrong with it. Could help me to figure it out?

**Comment by kroitor** [comment]
Your `markets` variable seems incorrect. You're using market ids as they are on Bittrex, but in ccxt we use unified symbols. To get the list of symbols available with Bittrex do:

```
```

**Comment by kroitor** [comment]
Can you please try this example: https://github.com/ccxt-dev/ccxt/blob/master/examples/py/async-bittrex-orderbook.py ? Does it work stable for you?

**Comment by dhmk815** [comment]
Thanks for your reply. 
However, I think it doesn't matter of `markets` variable. I have already tested before. It works. I know I can use symbols in ccxt.
The thing is that when I run this code at first several times. No error happen.
But, after several consequent running, sometimes I got that error message.

**Comment by kroitor** [comment]
It looks like you're trying to call all orderbooks simultaneously in asynchronous mode, whereas Bittrex can actually rate-limit your requests to 1 per second... We need to see if continuous fetching of one order book works stable for you, and then we will move on to multiple order books.

**Comment by dhmk815** [comment]
Yes, your example above works stable. I've just checked it.

**Comment by kroitor** [comment]
@dhmk815 ok, then this is most likely due to an attempt to fetch them all at once in a split second. Bittrex won't allow that (in fact no exchange likes that). Can you fetch them sequentially?

**Comment by dhmk815** [comment]
Yes, I can. But, I am trying to fetch all of them at once. This is what I want to do.

**Comment by kroitor** [comment]
> But, I am trying to fetch all of them at once. This is what I want to do.

But most exchanges won't allow that... They force you to do that sequentially.

**Comment by dhmk815** [comment]
Is there a possibility of problem in socket buffer size? There is an error message `n = self._sock.send(data)`.

**Comment by kroitor** [comment]
@dhmk815 that error message basically tells you, that an SSL connection to Bittrex has malfunctioned, and that can be caused by Bittrex closing your connections if there are making too many of them at once.

**Comment by dhmk815** [comment]
@kroitor I see. I think I have to split many requests.

**Comment by dhmk815** [comment]
@kroitor Thank you for your help. I am closing this issue.

**Comment by kroitor** [comment]
>  I think I have to split many requests.

Yes, because, as you see it yourself, if you do it sequentially, it works stable. See this example on how to fetch multiple symbols sequentially (it's for tickers, but orderbooks are the same): https://github.com/ccxt-dev/ccxt/blob/master/examples/py/async-generator-multiple-tickers.py

Hope it helps.

**Comment by amitkot** [comment]
Hi,
I'm getting this error when running a single query:

```python
async def _test1(loop):
    return await ccxt.binance().fetch_trades(symbol='OMG/ETH', limit=1)

if __name__ == '__main__':
    log = logging.getLogger('main')
    log.info('Starting event loop')
    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(_test1(loop))
    finally:
        log.info('Closing event loop')
        loop.close()
```

Output:
```
/bin/python /Users/amit/src/kyber/sanity-price-monitor/pricemonitor/datasource/exchanges.py
Fatal write error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x110f98b70>
transport: <_SelectorSocketTransport fd=9>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 761, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x110f98b70>
transport: <_SelectorSocketTransport closing fd=9>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 761, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/sslproto.py", line 646, in _process_write_backlog
    self._transport.write(chunk)
  File "/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 765, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 645, in _fatal_error
    self._force_close(exc)
  File "/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 657, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 574, in call_soon
    self._check_closed()
  File "/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

The odd thing is that when I run the query directly without the try-except it works fine.

**Comment by kroitor** [comment]
@amitkot can you post a minimal, but a complete sample of code that can be copy-pasted and run to reproduce your problem?

**Comment by amitkot** [comment]
@kroitor Complete snippet:
```python
import asyncio

import ccxt.async as ccxt


async def _test1():
    print(await ccxt.binance().fetch_trades(symbol='OMG/ETH', limit=1))


def option1():
    if __name__ == '__main__':
        loop = asyncio.get_event_loop()
        try:
            loop.run_until_complete(_test1())
        finally:
            loop.close()


def option2():
    asyncio.get_event_loop().run_until_complete(_test1())


# Uncomment one of the options:
# option1()  # Crashes
# option2()  # Works fine
```

Why not close the default aio loop at the end of the program?

Thanks!

**Comment by amitkot** [comment]
@kroitor Could you reopen this issue, or should I create a new one?

Thanks!

**Comment by kroitor** [comment]
@amitkot try this:

```Python
import asyncio

import ccxt.async as ccxt

exchange = ccxt.binance()

async def _test1():
    print(await exchange.fetch_trades(symbol='OMG/ETH', limit=1))


def option1():
    if __name__ == '__main__':
        loop = asyncio.get_event_loop()
        loop.run_until_complete(_test1())

option1() 
```

Does it crash this way?
